services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: art_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  eureka:
    build: ./Eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    build: ./ApiGateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    networks:
      - backend

  order-ms:
    build: ./Order-ms
    container_name: order-ms
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/art_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
      - eureka
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend: